// <auto-generated />
namespace ProjetoAgendamento.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Especialidade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Especialidade));
        
        string IMigrationMetadata.Id
        {
            get { return "201511102341369_Especialidade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
